### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by Ibrahim-Islam** [axefrog/SimpleBrowser#123]
Is it possible to take screenshot using SimpleBrowser?
If not then what could be the alternative to it?

**Comment by axefrog** [comment]
SimpleBrowser does not have a rendering engine, no. Try www.awesomium.com.

On 3 February 2015 at 20:46, Ibrahim Islam <notifications@github.com> wrote:

> Is it possible to take screenshot using SimpleBrowser?
> If not then what could be the alternative to it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/axefrog/SimpleBrowser/issues/123>.
>



-- 
*Google*: axefrog@gmail.com
*Skype*: axefrog
*Twitter*: @NathanRidley
*Website*: http://axefrog.com / http://nathanridley.com
*Phone: *+61 (0) 475 072789
