### ISSUE TITLE
Error at SimpleBrowser.Browser.get_XDocument()

### ISSUE THREAD

**Issue by budmul** [axefrog/SimpleBrowser#125]
Hi Guys,

I'm using FindElements(By.TagName("option")) in my code. The issue that I have is the code is working in my development machine, but after I publish it to the server, it failed. 

Below are the stack trace:
at SimpleBrowser.Browser.get_XDocument()     
at SimpleBrowser.Browser.FindElements(String tagName)     
at SimpleBrowser.Browser.Find(String tagName, Object elementAttributes)     
at SimpleBrowser.WebDriver.BrowserWrapper.Find(String query, Object param)     
at SimpleBrowser.WebDriver.SimpleBrowserDriver.CreateSearchContext(IBrowser my)     
at SimpleBrowser.WebDriver.SimpleBrowserDriver.FindElements(By by)     

Any idea how I can solve this? I already re-build and re-publish the code to server 3 times, but the error still exist.

**Comment by Teun** [comment]
What i always do is saving the current HTML to a file or to the console
output. This may be different from what you expect. Did you try to look at
the last exception. You can also use the RequestLogged event to inspect.

Teun
Op 13 feb. 2015 07:26 schreef "budmul" <notifications@github.com>:

**Comment by budmul** [comment]
Hi Teun,

Thanks for the reply. I will try to save the current HTML and see the result.

Btw, where can I found the RequestLogged event?

**Comment by Teun** [comment]
It is a public event on Browser.

T
Op 13 feb. 2015 07:51 schreef "budmul" <notifications@github.com>:

**Comment by kevingy** [comment]
This looks like HTML parser crash due to malformed input HTML. (The HTML parser doesn't run and the XDocument isn't created until a Find() is attempted.) The parser is failing to make a valid XML document from the input HTML.

Can you share the source HTML or URL? That would make debugging this issue a lot easier.

**Comment by kevingy** [comment]
@budmul Did you resolve your issue? Can this be closed?

**Comment by budmul** [comment]
Hi @kevingy, 

Sorry for my late reply, this issue is not resolved yet. I will check this again today. Will give you response soon.

**Comment by budmul** [comment]
Guys, I solve this issue. It is cause by the website not SimpleBrowser. Thanks for all responses, it help me to check and localize the error.
