### ISSUE TITLE
Getting Response Headers

### ISSUE THREAD

**Issue by DriveU** [axefrog/SimpleBrowser#127]
Is there a way by which I Navigate to a page and thereafter want to pull out all Response Headers and search for some text in each Header because my test demands something like this.

**Comment by Teun** [comment]
The Browser class exposes a public event called RequestLogged. This will fire after every request. It passes a reference to the Browser and an HttpRequestLog, which among other things, contains a RequestHeaders collection and a ResponseHeaders collection. What you typically do in a test is this:

    Browser b = new Browser();
    HttpRequestLog lastRequest = null;
    b.RequestLogged += (br, l) =>
    {
        lastRequest = l;
    };
    // Do stuff with browser

    // Assert your tests using the reference to the last request.

**Comment by DriveU** [comment]
Can you be kind enough to Elaborate a bit more on this example let me explain this I was doing all sorts of funny things with proxy and then a Web Client not knowing all of this is available in SimpleBrowser itself.
// DO stuff with browser means what ? I am sorry I am troubling you but my deadline has eeaten up my thinking completely

**Comment by DriveU** [comment]
we are using DataAnalytics I need to verify if all those pixels have fired On page load

**Comment by Teun** [comment]
I was giving an example of how you would use this in a unit test. 

However, this is not what you are trying to do. I'm afraid that SimpleBrowser is not going to solve your situation. It doesn't make image requests. It does as few requests as possible. In a headless browser, downloading images is normally not what you want to do. 

What you try to do is maybe better achieved using a proxy like Fiddler? Or is it something you want to check automatically? Then maybe a more full-fledged browser like PhantomJS + WebDriver. But I'm not sure how to make that log all requests.

**Comment by DriveU** [comment]
I meant all the ResponseHeaders in a browser Session from start to finish

**Comment by Teun** [comment]
I added a section to our wiki about logging data and getting the headers info for a whole session. But this will obviously not contain data for requests that SimpleBrowser just doesn't do. Like pixels.
https://github.com/axefrog/SimpleBrowser/wiki/Tutorial#log-requests
