### ISSUE TITLE
HtmlLogTemplate error

### ISSUE THREAD

**Issue by wezzix** [axefrog/SimpleBrowser#131]
I ran the logging according to the sample in readme.md, and got the following printed at the top of the html file. Changing them to log.ResponseCode and log.ToString() respectively resolved the issue.

Line: 640\t Col: 62\t Error: 'SimpleBrowser.HttpRequestLog' does not contain a definition for 'StatusCode' and no extension method 'StatusCode' accepting a first argument of type 'SimpleBrowser.HttpRequestLog' could be found (are you missing a using directive or an assembly reference?)
Line: 723\t Col: 73\t Error: 'SimpleBrowser.HttpRequestLog' does not contain a definition for 'ParsedHtml' and no extension method 'ParsedHtml' accepting a first argument of type 'SimpleBrowser.HttpRequestLog' could be found (are you missing a using directive or an assembly reference?)

**Comment by kevingy** [comment]
Good catch. Thanks!

**Comment by wezzix** [comment]
Ah, that too. I was a bit unclear, but I meant the HtmlLogTemplate.cshtml file at line 199 and 226, doesn't seem to run properly. 
`@log.StatusCode`
`<input type="hidden" id="html-@i" value="@HttpUtility.HtmlEncode(log.ParsedHtml ?? "")" />`
Cheers.

**Comment by kevingy** [comment]
Ah, I see. You were clear. It was my misunderstanding.

These two errors were caused by two different code changes. One is easy to fix. The other is more involved.  I'll get to work on it.

**Comment by kevingy** [comment]
It wasn't as involved as I thought it would be.
