### ISSUE TITLE
browser.CurrentHtml dont work polish letters 

### ISSUE THREAD

**Issue by hiroszi** [axefrog/SimpleBrowser#136]
Hi
 I have problem with encoding browser.CurrentHtml to UTF-8

**Comment by kevingy** [comment]
I'm happy to help, but you really will need to provide more detail. What is the URL of the page you are accessing? What is the problem you are having? What are you trying to accomplish?

**Comment by hiroszi** [comment]
URL: http://obejrzyjonline.pl/letters.html
![image](https://cloud.githubusercontent.com/assets/11850685/7500062/b4aadf06-f42b-11e4-804c-48e8ea1f2cd1.png)

:)

**Comment by axefrog** [comment]
Not sure if you're aware, but the command window is not good at displaying Unicode characters. Output to a text file and check the result there; you may find that there is no issue at all and that you were simply encountering a limitation of the command window.

**Comment by hiroszi** [comment]
![image](https://cloud.githubusercontent.com/assets/11850685/7504632/268ef6fa-f44c-11e4-913a-0059e3213ef5.png)

MessageBox too wrong :/
:(

**Comment by kevingy** [comment]
This is an encoding problem, regardless of the method used to output. I wrote the content to a file to be sure. The file contains incorrect characters.

Here's the SimpleBrowser code in question:
```
using (IHttpWebResponse response = req.GetResponse()) 
{
Encoding responseEncoding = Encoding.UTF8; //default
string charSet = response.CharacterSet;
if (!String.IsNullOrEmpty(charSet))
{
	try
	{
		responseEncoding = Encoding.GetEncoding(charSet);
	}
	catch (ArgumentException)
	{
		responseEncoding = Encoding.UTF8; // try using utf8
	}
}
}
```

As seen here, SimpleBrowser correctly uses UTF-8 by default. If the .NET HttpWebResponse.CharacterSet property indicates a specific character set, that character set is used. The HttpWebResponse.CharacterSet property is set by the Content-Type HTTP header. If this header is not specified or if it is specified, but the charset is not specified, .NET defaults to "ISO-8859-1". In your case, this is precisely what is happening. Your web server is returning "Content-Type: text/html", but not specifying UTF-8 in the header.

I will work on fixing this specific issue. Blindly trusting that .NET is accurately detecting the character set is obviously inappropriate. In addition to checking that the CharacterSet property is null or empty, the Content-Type HTTP header needs examination to determine if .NET is accurately reporting the character set.

There is, however, a larger issue. That being neither .NET or SimpleBrowser examine the HTML content to determine the character set. That is, ONLY the Content-Type HTTP header is used to determine the character set. The HTML5 charset meta tag (that is being used in the example URL in this issue) and the pre-HTML5 http-eqiv meta tag are inappropriately ignored.

**Comment by kevingy** [comment]
@hiroszi The code change referenced above should resolve your issue. Please try it. If it resolves your problem, please close this issue. Thanks!
