### ISSUE TITLE
Add the option value if its null

### ISSUE THREAD

**Issue by ajaip1** [axefrog/SimpleBrowser#141]
Hi,
I have successfully get the page, but some dropdown values are empty because this is populated by some javascript function, so, in this case we can't use find method because there is no values for selection. so how we can add those values in dropdown and then set the value for drop down.

If any help then great appreciate.

Thanks,
Ajai

**Comment by kevingy** [comment]
@ajaip1,

This topic is covered in the SimpleBrowser Tutorial Wiki:

https://github.com/axefrog/SimpleBrowser/wiki/Tutorial

Please refer to the section titled "Working with complex forms".

Kevin
